project_id = "ecmtctwovkheohqwahvt"

[functions.send-signup-confirmation]
verify_jwt = false

[functions.transcribe-articulation]
verify_jwt = false

[functions.upload-child-document]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.delete-logopedist]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.confirm-logopedist-email]
verify_jwt = false

[functions.archive-and-delete-user]
verify_jwt = false

[functions.check-old-pending-tests]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

